# DATA WRANGLING NHL PROJECT
## BAIS:3250 Data Wrangling
### Jacob Johnsen, Lucas Durflinger, Landon Doering
#### 04/16/2026
---

## File Library
---

- `game_teams_stats.csv`
- `game.csv`
- `team_info.csv`

<br>

## Import Library
---

In [1]:
import pandas as pd
import requests
from pandas import json_normalize

<br>

# Load Kaggle Datasets
---

In [2]:
#read in files
game_teams_stats = pd.read_csv("game_teams_stats.csv")
game = pd.read_csv("game.csv")
team_info = pd.read_csv("team_info.csv")

#display team_info
display(team_info.head(15))

#display game_teams_stats
display(game_teams_stats.head(15))

#display game
display(game.head(15))

,team_id,franchiseId,shortName,teamName,abbreviation,link
0,1,23,New Jersey,Devils,NJD,/api/v1/teams/1
1,4,16,Philadelphia,Flyers,PHI,/api/v1/teams/4
2,26,14,Los Angeles,Kings,LAK,/api/v1/teams/26
3,14,31,Tampa Bay,Lightning,TBL,/api/v1/teams/14
4,6,6,Boston,Bruins,BOS,/api/v1/teams/6
5,3,10,NY Rangers,Rangers,NYR,/api/v1/teams/3
6,5,17,Pittsburgh,Penguins,PIT,/api/v1/teams/5
7,17,12,Detroit,Red Wings,DET,/api/v1/teams/17
8,28,29,San Jose,Sharks,SJS,/api/v1/teams/28
9,18,34,Nashville,Predators,NSH,/api/v1/teams/18
10,23,20,Vancouver,Canucks,VAN,/api/v1/teams/23
11,16,11,Chicago,Blackhawks,CHI,/api/v1/teams/16
12,9,30,Ottawa,Senators,OTT,/api/v1/teams/9
13,8,1,Montreal,Canadiens,MTL,/api/v1/teams/8
14,30,37,Minnesota,Wild,MIN,/api/v1/teams/30

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,powerPlayOpportunities,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked,startRinkSide
0,2016020045,4,away,False,REG,Dave Hakstol,4.0,27.0,30.0,6.0,4.0,2.0,50.9,12.0,9.0,11.0,left
1,2016020045,16,home,True,REG,Joel Quenneville,7.0,28.0,20.0,8.0,3.0,2.0,49.1,16.0,8.0,9.0,left
2,2017020812,24,away,True,OT,Randy Carlyle,4.0,34.0,16.0,6.0,3.0,1.0,43.8,7.0,4.0,14.0,right
3,2017020812,7,home,False,OT,Phil Housley,3.0,33.0,17.0,8.0,2.0,1.0,56.2,5.0,6.0,14.0,right
4,2015020314,21,away,True,REG,Patrick Roy,4.0,29.0,17.0,9.0,3.0,1.0,45.7,13.0,5.0,20.0,left
5,2015020314,52,home,False,REG,Paul Maurice,1.0,21.0,22.0,11.0,2.0,0.0,54.3,13.0,7.0,9.0,left
6,2015020849,52,away,False,REG,Paul Maurice,1.0,21.0,21.0,10.0,4.0,0.0,31.4,4.0,14.0,16.0,left
7,2015020849,12,home,True,REG,Bill Peters,2.0,29.0,16.0,8.0,5.0,2.0,68.6,12.0,11.0,13.0,left
8,2017020586,20,away,False,REG,Glen Gulutzan,1.0,23.0,20.0,19.0,3.0,0.0,54.7,10.0,4.0,7.0,right
9,2017020586,24,home,True,REG,Randy Carlyle,2.0,41.0,15.0,13.0,6.0,1.0,45.3,13.0,4.0,21.0,right
10,2016020610,15,away,True,REG,Barry Trotz,4.0,39.0,19.0,8.0,2.0,1.0,46.6,8.0,5.0,24.0,left
11,2016020610,8,home,False,REG,Michel Therrien,1.0,23.0,27.0,4.0,4.0,1.0,53.4,12.0,7.0,18.0,left
12,2015020606,10,away,False,REG,Mike Babcock,1.0,26.0,24.0,19.0,4.0,1.0,56.9,6.0,2.0,7.0,left
13,2015020606,26,home,True,REG,Darryl Sutter,2.0,41.0,23.0,10.0,2.0,0.0,43.1,12.0,2.0,14.0,left
14,2017020240,23,away,False,REG,Travis Green,1.0,20.0,11.0,27.0,5.0,0.0,47.5,13.0,5.0,15.0,right

,game_id,season,type,date_time_GMT,away_team_id,home_team_id,away_goals,home_goals,outcome,home_rink_side_start,venue,venue_link,venue_time_zone_id,venue_time_zone_offset,venue_time_zone_tz
0,2016020045,20162017,R,2016-10-19T00:30:00Z,4,16,4,7,home win REG,right,United Center,/api/v1/venues/null,America/Chicago,-5,CDT
1,2017020812,20172018,R,2018-02-07T00:00:00Z,24,7,4,3,away win OT,left,KeyBank Center,/api/v1/venues/null,America/New_York,-4,EDT
2,2015020314,20152016,R,2015-11-24T01:00:00Z,21,52,4,1,away win REG,right,MTS Centre,/api/v1/venues/null,America/Winnipeg,-5,CDT
3,2015020849,20152016,R,2016-02-17T00:00:00Z,52,12,1,2,home win REG,right,PNC Arena,/api/v1/venues/null,America/New_York,-4,EDT
4,2017020586,20172018,R,2017-12-30T03:00:00Z,20,24,1,2,home win REG,left,Honda Center,/api/v1/venues/null,America/Los_Angeles,-7,PDT
5,2016020610,20162017,R,2017-01-10T00:30:00Z,15,8,4,1,away win REG,right,Centre Bell,/api/v1/venues/null,America/Montreal,-4,EDT
6,2015020606,20152016,R,2016-01-08T03:30:00Z,10,26,1,2,home win REG,right,STAPLES Center,/api/v1/venues/null,America/Los_Angeles,-7,PDT
7,2017020240,20172018,R,2017-11-10T03:00:00Z,23,24,1,4,home win REG,left,Honda Center,/api/v1/venues/null,America/Los_Angeles,-7,PDT
8,2017020624,20172018,R,2018-01-05T02:00:00Z,29,21,0,2,home win REG,right,Pepsi Center,/api/v1/venues/null,America/Denver,-6,MDT
9,2015020346,20152016,R,2015-11-29T00:00:00Z,22,5,3,2,away win OT,left,CONSOL Energy Center,/api/v1/venues/null,America/New_York,-4,EDT
10,2017020221,20172018,R,2017-11-07T01:30:00Z,52,25,4,1,away win REG,right,American Airlines Center,/api/v1/venues/null,America/Chicago,-5,CDT
11,2016020298,20162017,R,2016-11-24T03:30:00Z,2,26,2,4,home win REG,right,STAPLES Center,/api/v1/venues/null,America/Los_Angeles,-7,PDT
12,2017020731,20172018,R,2018-01-23T02:00:00Z,2,53,2,3,home win OT,left,Gila River Arena,/api/v1/venues/null,America/Phoenix,-7,MST
13,2016020205,20162017,R,2016-11-11T02:00:00Z,52,53,3,2,away win REG,left,Gila River Arena,/api/v1/venues/null,America/Phoenix,-7,MST
14,2016020246,20162017,R,2016-11-18T00:00:00Z,52,4,2,5,home win REG,right,Wells Fargo Center,/api/v1/venues/null,America/New_York,-4,EDT

<br>

# Inspect the DataFrames
---

In [3]:
#inspect column names
print("game_teams_stats columns:")
print(game_teams_stats.columns.tolist())

print("\ngame columns:")
print(game.columns.tolist())

print("\nteam_info columns:")
print(team_info.columns.tolist())

game_teams_stats columns:
['game_id', 'team_id', 'HoA', 'won', 'settled_in', 'head_coach', 'goals', 'shots', 'hits', 'pim', 'powerPlayOpportunities', 'powerPlayGoals', 'faceOffWinPercentage', 'giveaways', 'takeaways', 'blocked', 'startRinkSide']

game columns:
['game_id', 'season', 'type', 'date_time_GMT', 'away_team_id', 'home_team_id', 'away_goals', 'home_goals', 'outcome', 'home_rink_side_start', 'venue', 'venue_link', 'venue_time_zone_id', 'venue_time_zone_offset', 'venue_time_zone_tz']

team_info columns:
['team_id', 'franchiseId', 'shortName', 'teamName', 'abbreviation', 'link']

In [4]:
#find NA values for game_teams_stats
print(game_teams_stats.isnull().sum())

game_id                       0
team_id                       0
HoA                           0
won                           0
settled_in                    0
head_coach                   28
goals                         8
shots                         8
hits                       4928
pim                           8
powerPlayOpportunities        8
powerPlayGoals                8
faceOffWinPercentage      22148
giveaways                  4928
takeaways                  4928
blocked                    4928
startRinkSide              2392
dtype: int64

In [5]:
#find NA values for game
print(game.isnull().sum())

game_id                      0
season                       0
type                         0
date_time_GMT                0
away_team_id                 0
home_team_id                 0
away_goals                   0
home_goals                   0
outcome                      0
home_rink_side_start      1196
venue                        0
venue_link                   0
venue_time_zone_id           0
venue_time_zone_offset       0
venue_time_zone_tz           0
dtype: int64

In [6]:
#find NA values for team_info
print(team_info.isnull().sum())

team_id         0
franchiseId     0
shortName       0
teamName        0
abbreviation    0
link            0
dtype: int64

<br>

# Appropriately Shrink Datasets 
---

In [7]:
#shink game dataframe to only necessary data
game_small = game[["game_id", "season", "date_time_GMT"]]
game_small.head()

      game_id    season         date_time_GMT
0  2016020045  20162017  2016-10-19T00:30:00Z
1  2017020812  20172018  2018-02-07T00:00:00Z
2  2015020314  20152016  2015-11-24T01:00:00Z
3  2015020849  20152016  2016-02-17T00:00:00Z
4  2017020586  20172018  2017-12-30T03:00:00Z

In [8]:
#shink team_info dataframe to only necessary data
team_info_small = team_info[["team_id", "shortName", "teamName", "abbreviation"]]
team_info_small.head()

   team_id     shortName   teamName abbreviation
0        1    New Jersey     Devils          NJD
1        4  Philadelphia     Flyers          PHI
2       26   Los Angeles      Kings          LAK
3       14     Tampa Bay  Lightning          TBL
4        6        Boston     Bruins          BOS

<br>

# Merge the Shrunk DataFrames Together
---

In [9]:
#merge game_small on game_teams_stats to create merged_df
merged_df = game_teams_stats.merge(
    game_small,
    on="game_id",
    how="left"
)

In [10]:
#show shape and display data
print(merged_df.shape)
merged_df.head()

(62890, 19)

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,powerPlayOpportunities,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked,startRinkSide,season,date_time_GMT
0,2016020045,4,away,False,REG,Dave Hakstol,4.0,27.0,30.0,6.0,4.0,2.0,50.9,12.0,9.0,11.0,left,20162017,2016-10-19T00:30:00Z
1,2016020045,16,home,True,REG,Joel Quenneville,7.0,28.0,20.0,8.0,3.0,2.0,49.1,16.0,8.0,9.0,left,20162017,2016-10-19T00:30:00Z
2,2017020812,24,away,True,OT,Randy Carlyle,4.0,34.0,16.0,6.0,3.0,1.0,43.8,7.0,4.0,14.0,right,20172018,2018-02-07T00:00:00Z
3,2017020812,7,home,False,OT,Phil Housley,3.0,33.0,17.0,8.0,2.0,1.0,56.2,5.0,6.0,14.0,right,20172018,2018-02-07T00:00:00Z
4,2015020314,21,away,True,REG,Patrick Roy,4.0,29.0,17.0,9.0,3.0,1.0,45.7,13.0,5.0,20.0,left,20152016,2015-11-24T01:00:00Z

In [11]:
#merge team_info_small on merged_df
merged_df = merged_df.merge(
    team_info_small,
    on="team_id",
    how="left"
)

In [12]:
#show shape and display data
print(merged_df.shape)
merged_df.head()

(62890, 22)

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,...,faceOffWinPercentage,giveaways,takeaways,blocked,startRinkSide,season,date_time_GMT,shortName,teamName,abbreviation
0,2016020045,4,away,False,REG,Dave Hakstol,4.0,27.0,30.0,6.0,...,50.9,12.0,9.0,11.0,left,20162017,2016-10-19T00:30:00Z,Philadelphia,Flyers,PHI
1,2016020045,16,home,True,REG,Joel Quenneville,7.0,28.0,20.0,8.0,...,49.1,16.0,8.0,9.0,left,20162017,2016-10-19T00:30:00Z,Chicago,Blackhawks,CHI
2,2017020812,24,away,True,OT,Randy Carlyle,4.0,34.0,16.0,6.0,...,43.8,7.0,4.0,14.0,right,20172018,2018-02-07T00:00:00Z,Anaheim,Ducks,ANA
3,2017020812,7,home,False,OT,Phil Housley,3.0,33.0,17.0,8.0,...,56.2,5.0,6.0,14.0,right,20172018,2018-02-07T00:00:00Z,Buffalo,Sabres,BUF
4,2015020314,21,away,True,REG,Patrick Roy,4.0,29.0,17.0,9.0,...,45.7,13.0,5.0,20.0,left,20152016,2015-11-24T01:00:00Z,Colorado,Avalanche,COL

# Inspect Our Newly Merged Dataset
---

In [13]:
#shows column names
print(merged_df.columns.tolist())

['game_id', 'team_id', 'HoA', 'won', 'settled_in', 'head_coach', 'goals', 'shots', 'hits', 'pim', 'powerPlayOpportunities', 'powerPlayGoals', 'faceOffWinPercentage', 'giveaways', 'takeaways', 'blocked', 'startRinkSide', 'season', 'date_time_GMT', 'shortName', 'teamName', 'abbreviation']

In [14]:
#show first 5 rows
merged_df.head(5)

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,...,faceOffWinPercentage,giveaways,takeaways,blocked,startRinkSide,season,date_time_GMT,shortName,teamName,abbreviation
0,2016020045,4,away,False,REG,Dave Hakstol,4.0,27.0,30.0,6.0,...,50.9,12.0,9.0,11.0,left,20162017,2016-10-19T00:30:00Z,Philadelphia,Flyers,PHI
1,2016020045,16,home,True,REG,Joel Quenneville,7.0,28.0,20.0,8.0,...,49.1,16.0,8.0,9.0,left,20162017,2016-10-19T00:30:00Z,Chicago,Blackhawks,CHI
2,2017020812,24,away,True,OT,Randy Carlyle,4.0,34.0,16.0,6.0,...,43.8,7.0,4.0,14.0,right,20172018,2018-02-07T00:00:00Z,Anaheim,Ducks,ANA
3,2017020812,7,home,False,OT,Phil Housley,3.0,33.0,17.0,8.0,...,56.2,5.0,6.0,14.0,right,20172018,2018-02-07T00:00:00Z,Buffalo,Sabres,BUF
4,2015020314,21,away,True,REG,Patrick Roy,4.0,29.0,17.0,9.0,...,45.7,13.0,5.0,20.0,left,20152016,2015-11-24T01:00:00Z,Colorado,Avalanche,COL

In [15]:
#save our dataframe to .csv file
merged_df.to_csv("merged_df.csv")

In [16]:
#print seasons in our dataframe
print(merged_df["season"].unique())

[20162017 20172018 20152016 20002001 20142015 20132014 20122013 20012002
 20112012 20102011 20092010 20082009 20072008 20062007 20022003 20032004
 20052006 20192020 20182019]

In [17]:
#read-in merged_df
merged_df = pd.read_csv("merged_df.csv")

#take the three seasons and sort by time
project_df = merged_df[merged_df["season"].isin([20152016, 20162017, 20172018])].copy()
project_df = project_df.sort_values(by="date_time_GMT", ascending=True).reset_index(drop=True)

#count values and sort index
print(project_df["season"].value_counts().sort_index())
print(project_df.shape)

season
20152016    2642
20162017    2646
20172018    2726
Name: count, dtype: int64
(8014, 23)

In [18]:
#show datetime head
project_df[["date_time_GMT"]].head()

          date_time_GMT
0  2015-10-07T23:00:00Z
1  2015-10-07T23:00:00Z
2  2015-10-08T00:00:00Z
3  2015-10-08T00:00:00Z
4  2015-10-08T02:00:00Z

In [19]:
#show datetime tail
project_df[["date_time_GMT"]].tail()

             date_time_GMT
8009  2018-06-08T00:00:00Z
8010  2018-06-11T00:00:00Z
8011  2018-06-11T00:00:00Z
8012  2018-06-14T00:00:00Z
8013  2018-06-14T00:00:00Z

In [20]:
#convert our date column to datetime
project_df["date_time_GMT"] = pd.to_datetime(project_df["date_time_GMT"])

In [21]:
#convert to central timezone
project_df["date_time_CT"] = project_df["date_time_GMT"].dt.tz_convert("US/Central")

In [22]:
#drop unecessary columns
project_df = project_df[['game_id', 'team_id','season','date_time_CT','HoA','won','goals', 'shots', 'hits', 'pim', 'powerPlayOpportunities', 'powerPlayGoals', 'faceOffWinPercentage', 'giveaways', 'takeaways', 'blocked','teamName', 'abbreviation']].copy()

In [23]:
#display
display(project_df)

,game_id,team_id,season,date_time_CT,HoA,won,goals,shots,hits,pim,powerPlayOpportunities,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked,teamName,abbreviation
0,2015020001,10,20152016,2015-10-07 18:00:00-05:00,home,False,1.0,37.0,26.0,4.0,3.0,1.0,53.1,4.0,7.0,9.0,Maple Leafs,TOR
1,2015020001,8,20152016,2015-10-07 18:00:00-05:00,away,True,3.0,29.0,26.0,8.0,1.0,0.0,46.9,9.0,6.0,15.0,Canadiens,MTL
2,2015020002,16,20152016,2015-10-07 19:00:00-05:00,home,False,2.0,34.0,25.0,2.0,1.0,0.0,52.6,11.0,3.0,3.0,Blackhawks,CHI
3,2015020002,3,20152016,2015-10-07 19:00:00-05:00,away,True,3.0,27.0,43.0,4.0,0.0,0.0,47.4,13.0,10.0,15.0,Rangers,NYR
4,2015020003,23,20152016,2015-10-07 21:00:00-05:00,away,True,5.0,44.0,16.0,36.0,3.0,0.0,47.8,4.0,5.0,13.0,Canucks,VAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8009,2017030415,54,20172018,2018-06-07 19:00:00-05:00,home,False,3.0,31.0,39.0,12.0,2.0,1.0,52.5,15.0,22.0,11.0,Golden Knights,VGK
8010,2017030416,54,20172018,2018-06-10 19:00:00-05:00,away,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Golden Knights,VGK
8011,2017030416,15,20172018,2018-06-10 19:00:00-05:00,home,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Capitals,WSH
8012,2017030417,15,20172018,2018-06-13 19:00:00-05:00,away,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Capitals,WSH
8013,2017030417,54,20172018,2018-06-13 19:00:00-05:00,home,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Golden Knights,VGK

<br>

# Scrape API 
---

In [24]:
#format date
project_df["game_date"] = project_df["date_time_CT"].dt.strftime("%Y-%m-%d")

In [25]:
#drop duplicate dates and show unique dates (and count of unique dates)
unique_dates = sorted(project_df["game_date"].dropna().unique())
print(len(unique_dates))
#print(unique_dates)

677

In [26]:
#function that gets and scrapes API
def get_nhl_json(url):
    response = requests.get(url, timeout=30)
    response.raise_for_status()
    return response.json()

#empty list
all_api_games = []

for date_str in unique_dates:
    url = f"https://api-web.nhle.com/v1/score/{date_str}" #url
    
    try:
        data = get_nhl_json(url)
        
        if "games" in data and len(data["games"]) > 0:
            day_df = json_normalize(data["games"])
            day_df["query_date"] = date_str
            all_api_games.append(day_df)
            
    except Exception as e:
        print(f"Error on {date_str}: {e}")

In [27]:
#concat list to dataframe then display shape and head
api_games_df = pd.concat(all_api_games, ignore_index=True)
print(api_games_df.shape)
api_games_df.head(5)

(3993, 53)

,id,season,gameType,gameDate,startTimeUTC,easternUTCOffset,venueUTCOffset,tvBroadcasts,gameState,gameScheduleState,...,seriesStatus.seriesAbbrev,seriesStatus.seriesTitle,seriesStatus.seriesLetter,seriesStatus.neededToWin,seriesStatus.topSeedTeamAbbrev,seriesStatus.topSeedWins,seriesStatus.bottomSeedTeamAbbrev,seriesStatus.bottomSeedWins,seriesStatus.gameNumberOfSeries,periodDescriptor.otPeriods
0,2015020001,20152016,2,2015-10-07,2015-10-07T23:00:00Z,-04:00,-04:00,"[{'id': 282, 'market': 'N', 'countryCode': 'CA...",OFF,OK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015020002,20152016,2,2015-10-07,2015-10-08T00:00:00Z,-04:00,-05:00,"[{'id': 241, 'market': 'N', 'countryCode': 'US...",OFF,OK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015020003,20152016,2,2015-10-07,2015-10-08T02:00:00Z,-04:00,-06:00,"[{'id': 282, 'market': 'N', 'countryCode': 'CA...",OFF,OK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015020004,20152016,2,2015-10-07,2015-10-08T02:30:00Z,-04:00,-07:00,"[{'id': 241, 'market': 'N', 'countryCode': 'US...",OFF,OK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015020005,20152016,2,2015-10-08,2015-10-08T23:00:00Z,-04:00,-04:00,"[{'id': 292, 'market': 'A', 'countryCode': 'CA...",OFF,OK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
#drop unecessary columns
api_games_df = api_games_df[[
    "id",
    "season",
    "gameDate",
    "gameType",
    "gameState",
    "awayTeam.id",
    "awayTeam.abbrev",
    "awayTeam.score",
    "homeTeam.id",
    "homeTeam.abbrev",
    "homeTeam.score",
    "venue.default",
    "seriesStatus.seriesTitle",
    "seriesStatus.round"
]].copy()

In [29]:
#rename columns
api_games_df.columns = [
    "game_id",
    "season_api",
    "game_date_api",
    "game_type_api",
    "game_state_api",
    "away_team_id_api",
    "away_team_abbrev_api",
    "away_score_api",
    "home_team_id_api",
    "home_team_abbrev_api",
    "home_score_api",
    "venue_api", 
    "playoff_title_api", 
    "playoff_round_api"
]

In [30]:
#display
display(api_games_df)

,game_id,season_api,game_date_api,game_type_api,game_state_api,away_team_id_api,away_team_abbrev_api,away_score_api,home_team_id_api,home_team_abbrev_api,home_score_api,venue_api,playoff_title_api,playoff_round_api
0,2015020001,20152016,2015-10-07,2,OFF,8,MTL,3,10,TOR,1,Air Canada Centre,NaN,NaN
1,2015020002,20152016,2015-10-07,2,OFF,3,NYR,3,16,CHI,2,United Center,NaN,NaN
2,2015020003,20152016,2015-10-07,2,OFF,23,VAN,5,20,CGY,1,Scotiabank Saddledome,NaN,NaN
3,2015020004,20152016,2015-10-07,2,OFF,28,SJS,5,26,LAK,1,STAPLES Center,NaN,NaN
4,2015020005,20152016,2015-10-08,2,OFF,52,WPG,6,6,BOS,2,TD Garden,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3988,2017030411,20172018,2018-05-28,3,OFF,15,WSH,4,54,VGK,6,T-Mobile Arena,Stanley Cup Final,4.0
3989,2017030412,20172018,2018-05-30,3,OFF,15,WSH,3,54,VGK,2,T-Mobile Arena,Stanley Cup Final,4.0
3990,2017030413,20172018,2018-06-02,3,OFF,54,VGK,1,15,WSH,3,Verizon Center,Stanley Cup Final,4.0
3991,2017030414,20172018,2018-06-04,3,OFF,54,VGK,2,15,WSH,6,Verizon Center,Stanley Cup Final,4.0
3992,2017030415,20172018,2018-06-07,3,OFF,15,WSH,4,54,VGK,3,T-Mobile Arena,Stanley Cup Final,4.0

<br>

# Merge API onto Other Data

In [31]:
check = project_df[(project_df["abbreviation"] == "TOR") & (project_df["HoA"] == "home")]
display(check.head(5))

check_2 = api_games_df[api_games_df["home_team_abbrev_api"] == "TOR"]
display(check_2.head(5))

,game_id,team_id,season,date_time_CT,HoA,won,goals,shots,hits,pim,powerPlayOpportunities,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked,teamName,abbreviation,game_date
0,2015020001,10,20152016,2015-10-07 18:00:00-05:00,home,False,1.0,37.0,26.0,4.0,3.0,1.0,53.1,4.0,7.0,9.0,Maple Leafs,TOR,2015-10-07
46,2015020019,10,20152016,2015-10-10 18:00:00-05:00,home,False,4.0,41.0,27.0,14.0,4.0,1.0,50.7,10.0,8.0,16.0,Maple Leafs,TOR,2015-10-10
242,2015020122,10,20152016,2015-10-26 18:30:00-05:00,home,False,3.0,27.0,27.0,10.0,2.0,0.0,40.0,9.0,16.0,8.0,Maple Leafs,TOR,2015-10-26
321,2015020157,10,20152016,2015-10-31 18:00:00-05:00,home,False,0.0,21.0,19.0,11.0,4.0,0.0,41.7,5.0,8.0,11.0,Maple Leafs,TOR,2015-10-31
337,2015020169,10,20152016,2015-11-02 18:30:00-06:00,home,True,4.0,26.0,30.0,4.0,5.0,2.0,52.4,7.0,8.0,16.0,Maple Leafs,TOR,2015-11-02

,game_id,season_api,game_date_api,game_type_api,game_state_api,away_team_id_api,away_team_abbrev_api,away_score_api,home_team_id_api,home_team_abbrev_api,home_score_api,venue_api,playoff_title_api,playoff_round_api
0,2015020001,20152016,2015-10-07,2,OFF,8,MTL,3,10,TOR,1,Air Canada Centre,NaN,NaN
18,2015020019,20152016,2015-10-10,2,OFF,9,OTT,5,10,TOR,4,Air Canada Centre,NaN,NaN
121,2015020122,20152016,2015-10-26,2,OFF,53,ARI,4,10,TOR,3,Air Canada Centre,NaN,NaN
156,2015020157,20152016,2015-10-31,2,OFF,5,PIT,4,10,TOR,0,Air Canada Centre,NaN,NaN
168,2015020169,20152016,2015-11-02,2,OFF,25,DAL,1,10,TOR,4,Air Canada Centre,NaN,NaN

In [32]:
final_df = pd.merge(
    project_df,
    api_games_df,
    on="game_id",
    how="left",
    suffixes=("", "_api")
)

display(final_df.head(20))

print(final_df.columns)

,game_id,team_id,season,date_time_CT,HoA,won,goals,shots,hits,pim,...,game_state_api,away_team_id_api,away_team_abbrev_api,away_score_api,home_team_id_api,home_team_abbrev_api,home_score_api,venue_api,playoff_title_api,playoff_round_api
0,2015020001,10,20152016,2015-10-07 18:00:00-05:00,home,False,1.0,37.0,26.0,4.0,...,OFF,8.0,MTL,3.0,10.0,TOR,1.0,Air Canada Centre,NaN,NaN
1,2015020001,8,20152016,2015-10-07 18:00:00-05:00,away,True,3.0,29.0,26.0,8.0,...,OFF,8.0,MTL,3.0,10.0,TOR,1.0,Air Canada Centre,NaN,NaN
2,2015020002,16,20152016,2015-10-07 19:00:00-05:00,home,False,2.0,34.0,25.0,2.0,...,OFF,3.0,NYR,3.0,16.0,CHI,2.0,United Center,NaN,NaN
3,2015020002,3,20152016,2015-10-07 19:00:00-05:00,away,True,3.0,27.0,43.0,4.0,...,OFF,3.0,NYR,3.0,16.0,CHI,2.0,United Center,NaN,NaN
4,2015020003,23,20152016,2015-10-07 21:00:00-05:00,away,True,5.0,44.0,16.0,36.0,...,OFF,23.0,VAN,5.0,20.0,CGY,1.0,Scotiabank Saddledome,NaN,NaN
5,2015020003,20,20152016,2015-10-07 21:00:00-05:00,home,False,1.0,30.0,28.0,38.0,...,OFF,23.0,VAN,5.0,20.0,CGY,1.0,Scotiabank Saddledome,NaN,NaN
6,2015020004,26,20152016,2015-10-07 21:30:00-05:00,home,False,1.0,20.0,33.0,36.0,...,OFF,28.0,SJS,5.0,26.0,LAK,1.0,STAPLES Center,NaN,NaN
7,2015020004,28,20152016,2015-10-07 21:30:00-05:00,away,True,5.0,32.0,19.0,24.0,...,OFF,28.0,SJS,5.0,26.0,LAK,1.0,STAPLES Center,NaN,NaN
8,2015020005,52,20152016,2015-10-08 18:00:00-05:00,away,True,6.0,32.0,32.0,6.0,...,OFF,52.0,WPG,6.0,6.0,BOS,2.0,TD Garden,NaN,NaN
9,2015020005,6,20152016,2015-10-08 18:00:00-05:00,home,False,2.0,31.0,31.0,2.0,...,OFF,52.0,WPG,6.0,6.0,BOS,2.0,TD Garden,NaN,NaN
10,2015020006,7,20152016,2015-10-08 18:00:00-05:00,home,False,1.0,27.0,11.0,0.0,...,OFF,9.0,OTT,3.0,7.0,BUF,1.0,First Niagara Center,NaN,NaN
11,2015020006,9,20152016,2015-10-08 18:00:00-05:00,away,True,3.0,22.0,22.0,6.0,...,OFF,9.0,OTT,3.0,7.0,BUF,1.0,First Niagara Center,NaN,NaN
12,2015020007,4,20152016,2015-10-08 18:30:00-05:00,away,False,2.0,25.0,26.0,6.0,...,OFF,4.0,PHI,2.0,14.0,TBL,3.0,Amalie Arena,NaN,NaN
13,2015020007,14,20152016,2015-10-08 18:30:00-05:00,home,True,3.0,32.0,25.0,6.0,...,OFF,4.0,PHI,2.0,14.0,TBL,3.0,Amalie Arena,NaN,NaN
14,2015020009,12,20152016,2015-10-08 19:00:00-05:00,away,False,1.0,26.0,11.0,6.0,...,OFF,12.0,CAR,1.0,18.0,NSH,2.0,Bridgestone Arena,NaN,NaN
15,2015020008,19,20152016,2015-10-08 19:00:00-05:00,home,True,3.0,31.0,22.0,13.0,...,OFF,22.0,EDM,1.0,19.0,STL,3.0,Scottrade Center,NaN,NaN
16,2015020008,22,20152016,2015-10-08 19:00:00-05:00,away,False,1.0,25.0,14.0,13.0,...,OFF,22.0,EDM,1.0,19.0,STL,3.0,Scottrade Center,NaN,NaN
17,2015020009,18,20152016,2015-10-08 19:00:00-05:00,home,True,2.0,25.0,15.0,6.0,...,OFF,12.0,CAR,1.0,18.0,NSH,2.0,Bridgestone Arena,NaN,NaN
18,2015020010,25,20152016,2015-10-08 19:30:00-05:00,home,True,3.0,24.0,23.0,6.0,...,OFF,5.0,PIT,0.0,25.0,DAL,3.0,American Airlines Center,NaN,NaN
19,2015020010,5,20152016,2015-10-08 19:30:00-05:00,away,False,0.0,37.0,21.0,10.0,...,OFF,5.0,PIT,0.0,25.0,DAL,3.0,American Airlines Center,NaN,NaN

Index(['game_id', 'team_id', 'season', 'date_time_CT', 'HoA', 'won', 'goals',
       'shots', 'hits', 'pim', 'powerPlayOpportunities', 'powerPlayGoals',
       'faceOffWinPercentage', 'giveaways', 'takeaways', 'blocked', 'teamName',
       'abbreviation', 'game_date', 'season_api', 'game_date_api',
       'game_type_api', 'game_state_api', 'away_team_id_api',
       'away_team_abbrev_api', 'away_score_api', 'home_team_id_api',
       'home_team_abbrev_api', 'home_score_api', 'venue_api',
       'playoff_title_api', 'playoff_round_api'],
      dtype='object')

In [33]:
#save as .csv file to take to next .ipynb for cleaning
final_df.to_csv("nhl_merged.csv", encoding = 'utf-8', sep = ',')

<br>